"""end time column in training sessions

Revision ID: 17cdacdd440b
Revises: a874f6103230
Create Date: 2026-06-30 10:38:49.909576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cdacdd440b'
down_revision = 'a874f6103230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EndTime', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('EndTime')

    # ### end Alembic commands ###
