"""added timestamp columns for booking actions

Revision ID: 281293698e14
Revises: a16d94ba4598
Create Date: 2026-06-26 08:23:08.690767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281293698e14'
down_revision = 'a16d94ba4598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ApprovedAt', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('CompletedAt', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('CancelledAt', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('RejectedAt', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('RejectedAt')
        batch_op.drop_column('CancelledAt')
        batch_op.drop_column('CompletedAt')
        batch_op.drop_column('ApprovedAt')

    # ### end Alembic commands ###
