"""empty message

Revision ID: 488c7738a4e2
Revises: 731982414606
Create Date: 2026-07-02 17:00:23.758951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488c7738a4e2'
down_revision = '731982414606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CancelReason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('CancelReason')

    # ### end Alembic commands ###
