"""end time not nullable

Revision ID: 4d57c9fbea6c
Revises: 17cdacdd440b
Create Date: 2026-06-30 10:50:21.010247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d57c9fbea6c'
down_revision = '17cdacdd440b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('EndTime',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('EndTime',
               existing_type=postgresql.TIME(),
               nullable=True)

    # ### end Alembic commands ###
