"""more cascade stuff

Revision ID: 6013735479b7
Revises: e0800939687b
Create Date: 2026-07-07 11:21:20.241814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6013735479b7'
down_revision = 'e0800939687b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_SessionId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_sessions', ['SessionId'], ['SessionId'], ondelete='CASCADE')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('departments_ManagerId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['ManagerId'], ['UserId'], ondelete='SET NULL')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('training_sessions_CourseId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_courses', ['CourseId'], ['CourseId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('training_sessions_CourseId_fkey'), 'training_courses', ['CourseId'], ['CourseId'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('departments_ManagerId_fkey'), 'users', ['ManagerId'], ['UserId'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_SessionId_fkey'), 'training_sessions', ['SessionId'], ['SessionId'])

    # ### end Alembic commands ###
