"""more user perms

Revision ID: 731982414606
Revises: 4c0d52f9d7d4
Create Date: 2026-07-02 08:10:19.722371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731982414606'
down_revision = '4c0d52f9d7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ManagerPerms', sa.Enum('Yes', 'No', name='manager_perms'), nullable=True))
        batch_op.add_column(sa.Column('AdminPerms', sa.Enum('Yes', 'No', name='admin_perms'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('AdminPerms')
        batch_op.drop_column('ManagerPerms')

    # ### end Alembic commands ###
