"""trainer perms column

Revision ID: 8d4b02657821
Revises: 8d7a1a46375b
Create Date: 2026-06-19 15:38:28.282004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4b02657821'
down_revision = '8d7a1a46375b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TrainerPerms', sa.Enum('Yes', 'No', name='trainer_perms'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('TrainerPerms')

    # ### end Alembic commands ###
