"""marked column in session

Revision ID: 8d7a1a46375b
Revises: a292cf5c9abc
Create Date: 2026-06-09 16:14:18.827752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7a1a46375b'
down_revision = 'a292cf5c9abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Marked', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('Marked')

    # ### end Alembic commands ###
