"""add notifications table

Revision ID: 8eb07359fca6
Revises: 488c7738a4e2
Create Date: 2026-07-07 10:05:06.793507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb07359fca6'
down_revision = '488c7738a4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('NotificationId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Message', sa.Text(), nullable=False),
    sa.Column('NotificationType', sa.Enum('Booking', 'Approval', 'Cancellation', 'System', name='notification_type'), nullable=False),
    sa.Column('IsRead', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('RelatedBookingId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RelatedBookingId'], ['bookings.BookingId'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('NotificationId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
