"""phone number nullable

Revision ID: a16d94ba4598
Revises: 8d4b02657821
Create Date: 2026-06-22 00:25:56.793410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16d94ba4598'
down_revision = '8d4b02657821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('Phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('JobTitle',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('JobTitle',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('Phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    # ### end Alembic commands ###
