"""added session status

Revision ID: a292cf5c9abc
Revises: a88b8ff8d8a3
Create Date: 2026-06-09 10:57:50.122979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a292cf5c9abc'
down_revision = 'a88b8ff8d8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.Enum('Completed', 'Not completed', name='session_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('Status')

    # ### end Alembic commands ###
