"""Training session status not nullable

Revision ID: a874f6103230
Revises: 281293698e14
Create Date: 2026-06-30 10:28:47.367775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a874f6103230'
down_revision = '281293698e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=postgresql.ENUM('Completed', 'Not completed', name='session_status'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=postgresql.ENUM('Completed', 'Not completed', name='session_status'),
               nullable=True)

    # ### end Alembic commands ###
