"""decided on column for bookings

Revision ID: a88b8ff8d8a3
Revises: ab16a0bcc295
Create Date: 2026-06-08 09:56:34.303549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88b8ff8d8a3'
down_revision = 'ab16a0bcc295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DecidedOn', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('DecidedOn')

    # ### end Alembic commands ###
