"""user id in attendance

Revision ID: ab16a0bcc295
Revises: 3676af4be68d
Create Date: 2026-06-05 10:46:03.935967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab16a0bcc295'
down_revision = '3676af4be68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['UserId'], ['UserId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('UserId')

    # ### end Alembic commands ###
