"""Added departments table and relationships

Revision ID: de826b662b1b
Revises: d9092a09b098
Create Date: 2026-06-04 10:00:07.186021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de826b662b1b'
down_revision = 'd9092a09b098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('DepartmentId', sa.Integer(), nullable=False),
    sa.Column('DepartmentName', sa.String(length=100), nullable=False),
    sa.Column('ManagerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ManagerId'], ['users.UserId'], ),
    sa.PrimaryKeyConstraint('DepartmentId')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DepartmentId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['DepartmentId'], ['DepartmentId'])
        batch_op.drop_column('BusinessArea')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BusinessArea', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('DepartmentId')

    op.drop_table('departments')
    # ### end Alembic commands ###
