"""cascade stuff

Revision ID: e0800939687b
Revises: 8eb07359fca6
Create Date: 2026-07-07 10:29:50.499560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0800939687b'
down_revision = '8eb07359fca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_BookingId_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attendance_UserId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['BookingId'], ['BookingId'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['UserId'], ['UserId'], ondelete='CASCADE')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_UserId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['UserId'], ['UserId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_UserId_fkey'), 'users', ['UserId'], ['UserId'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_UserId_fkey'), 'users', ['UserId'], ['UserId'])
        batch_op.create_foreign_key(batch_op.f('attendance_BookingId_fkey'), 'bookings', ['BookingId'], ['BookingId'])

    # ### end Alembic commands ###
