"""business ares to department id in courses

Revision ID: e20929c2f06e
Revises: de826b662b1b
Create Date: 2026-06-04 10:46:13.914698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20929c2f06e'
down_revision = 'de826b662b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DepartmentId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['DepartmentId'], ['DepartmentId'])
        batch_op.drop_column('BusinessArea')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BusinessArea', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('DepartmentId')

    # ### end Alembic commands ###
